# week 1 ...

Factory.define :weeklyreport_1, :class => Weeklyreport, :singleton => true do |w|
  w.weeklyReport_id '1'
  w.weeklyReport_1on1SpConv '1'
  w.weeklyReport_1on1GosPres '1'
  w.weeklyReport_1on1HsPres '1'
  w.staff_id '1'
  w.week_id '1'
  w.campus_id '1'
  w.weeklyReport_7upCompleted '0'
  w.weeklyReport_1on1SpConvStd '1'
  w.weeklyReport_1on1GosPresStd '1'
  w.weeklyReport_1on1HsPresStd '1'
  w.weeklyReport_7upCompletedStd '0'
  w.weeklyReport_cjVideo '1'
  w.weeklyReport_mda '1'
  w.weeklyReport_otherEVMats '1'
  w.weeklyReport_rlk '1'
  w.weeklyReport_siq '1'
  w.weeklyReport_notes 'one'
end

Factory.define :weeklyreport_2, :class => Weeklyreport, :singleton => true do |w|
  w.weeklyReport_id '2'
  w.weeklyReport_1on1SpConv '2'
  w.weeklyReport_1on1GosPres '2'
  w.weeklyReport_1on1HsPres '2'
  w.staff_id '2'
  w.week_id '1'
  w.campus_id '1'
  w.weeklyReport_7upCompleted '1'
  w.weeklyReport_1on1SpConvStd '2'
  w.weeklyReport_1on1GosPresStd '2'
  w.weeklyReport_1on1HsPresStd '2'
  w.weeklyReport_7upCompletedStd '0'
  w.weeklyReport_cjVideo '2'
  w.weeklyReport_mda '2'
  w.weeklyReport_otherEVMats '2'
  w.weeklyReport_rlk '2'
  w.weeklyReport_siq '2'
  w.weeklyReport_notes 'two'
end

Factory.define :weeklyreport_3, :class => Weeklyreport, :singleton => true do |w|
  w.weeklyReport_id '3'
  w.weeklyReport_1on1SpConv '3'
  w.weeklyReport_1on1GosPres '3'
  w.weeklyReport_1on1HsPres '3'
  w.staff_id '3'
  w.week_id '1'
  w.campus_id '1'
  w.weeklyReport_7upCompleted '1'
  w.weeklyReport_1on1SpConvStd '3'
  w.weeklyReport_1on1GosPresStd '3'
  w.weeklyReport_1on1HsPresStd '3'
  w.weeklyReport_7upCompletedStd '1'
  w.weeklyReport_cjVideo '3'
  w.weeklyReport_mda '3'
  w.weeklyReport_otherEVMats '3'
  w.weeklyReport_rlk '3'
  w.weeklyReport_siq '3'
  w.weeklyReport_notes 'three'
end

Factory.define :weeklyreport_4, :class => Weeklyreport, :singleton => true do |w|
  w.weeklyReport_id '4'
  w.weeklyReport_1on1SpConv '4'
  w.weeklyReport_1on1GosPres '4'
  w.weeklyReport_1on1HsPres '4'
  w.staff_id '4'
  w.week_id '1'
  w.campus_id '2'
  w.weeklyReport_7upCompleted '0'
  w.weeklyReport_1on1SpConvStd '4'
  w.weeklyReport_1on1GosPresStd '4'
  w.weeklyReport_1on1HsPresStd '4'
  w.weeklyReport_7upCompletedStd '0'
  w.weeklyReport_cjVideo '4'
  w.weeklyReport_mda '4'
  w.weeklyReport_otherEVMats '4'
  w.weeklyReport_rlk '4'
  w.weeklyReport_siq '4'
  w.weeklyReport_notes 'four'
end



# week 2 ...

Factory.define :weeklyreport_5, :class => Weeklyreport, :singleton => true do |w|
  w.weeklyReport_id '5'
  w.weeklyReport_1on1SpConv '5'
  w.weeklyReport_1on1GosPres '5'
  w.weeklyReport_1on1HsPres '5'
  w.staff_id '1'
  w.week_id '2'
  w.campus_id '1'
  w.weeklyReport_7upCompleted '0'
  w.weeklyReport_1on1SpConvStd '5'
  w.weeklyReport_1on1GosPresStd '5'
  w.weeklyReport_1on1HsPresStd '5'
  w.weeklyReport_7upCompletedStd '0'
  w.weeklyReport_cjVideo '5'
  w.weeklyReport_mda '5'
  w.weeklyReport_otherEVMats '5'
  w.weeklyReport_rlk '5'
  w.weeklyReport_siq '5'
  w.weeklyReport_notes 'five'
end

Factory.define :weeklyreport_6, :class => Weeklyreport, :singleton => true do |w|
  w.weeklyReport_id '6'
  w.weeklyReport_1on1SpConv '6'
  w.weeklyReport_1on1GosPres '6'
  w.weeklyReport_1on1HsPres '6'
  w.staff_id '2'
  w.week_id '2'
  w.campus_id '1'
  w.weeklyReport_7upCompleted '0'
  w.weeklyReport_1on1SpConvStd '6'
  w.weeklyReport_1on1GosPresStd '6'
  w.weeklyReport_1on1HsPresStd '6'
  w.weeklyReport_7upCompletedStd '0'
  w.weeklyReport_cjVideo '6'
  w.weeklyReport_mda '6'
  w.weeklyReport_otherEVMats '6'
  w.weeklyReport_rlk '6'
  w.weeklyReport_siq '6'
  w.weeklyReport_notes 'six'
end

Factory.define :weeklyreport_7, :class => Weeklyreport, :singleton => true do |w|
  w.weeklyReport_id '7'
  w.weeklyReport_1on1SpConv '7'
  w.weeklyReport_1on1GosPres '7'
  w.weeklyReport_1on1HsPres '7'
  w.staff_id '4'
  w.week_id '2'
  w.campus_id '2'
  w.weeklyReport_7upCompleted '0'
  w.weeklyReport_1on1SpConvStd '7'
  w.weeklyReport_1on1GosPresStd '7'
  w.weeklyReport_1on1HsPresStd '7'
  w.weeklyReport_7upCompletedStd '1'
  w.weeklyReport_cjVideo '7'
  w.weeklyReport_mda '7'
  w.weeklyReport_otherEVMats '7'
  w.weeklyReport_rlk '7'
  w.weeklyReport_siq '7'
  w.weeklyReport_notes 'seven'
end

Factory.define :weeklyreport_8, :class => Weeklyreport, :singleton => true do |w|
  w.weeklyReport_id '8'
  w.weeklyReport_1on1SpConv '8'
  w.weeklyReport_1on1GosPres '8'
  w.weeklyReport_1on1HsPres '8'
  w.staff_id '5'
  w.week_id '2'
  w.campus_id '2'
  w.weeklyReport_7upCompleted '1'
  w.weeklyReport_1on1SpConvStd '8'
  w.weeklyReport_1on1GosPresStd '8'
  w.weeklyReport_1on1HsPresStd '8'
  w.weeklyReport_7upCompletedStd '0'
  w.weeklyReport_cjVideo '8'
  w.weeklyReport_mda '8'
  w.weeklyReport_otherEVMats '8'
  w.weeklyReport_rlk '8'
  w.weeklyReport_siq '8'
  w.weeklyReport_notes 'seven'
end

